### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by kamalsamantaray** [shrey6162/Questionnaire.github.io#4]
Please upload the project report

**Comment by shrey6162** [comment]
[Minor Project Report.pdf](https://github.com/shrey6162/Questionnaire.github.io/files/7109231/Minor.Project.Report.pdf)

**Comment by shrey6162** [comment]
Go ahead you can take ideas from this project report.....

**Comment by kamalsamantaray** [comment]
Thanks shreya for your permission to use your project.
And I see that it is a minor project report ,if u have any detailed final
report please send it to me if not it's ok .
Thanks & Regards
Kamal
